#adapted from example in docker documentation
version: '3'

services:
  web:
    restart: always
    build: .
    volumes:
      - .:/code
    depends_on:
      - redis
    links:
      - redis:redis
    expose:
      - 8000
    user: "1001:1002" #system dependent
    environment: 
      - GOOGLE_APPLICATION_CREDENTIALS=/code/mysite/cins465-google-creds.json
   #  command: python /code/mysite/manage.py runserver 0.0.0.0:8000
    working_dir: /code/mysite
    command: daphne -b 0.0.0.0 -p 8000 mysite.asgi:application
  
  wasm:
    build: ./wasm/
    working_dir: /code/wasm-test/myproject/
    # user: "1001:1002" #system dependent
    volumes: 
      - .:/code

#   nginx:
#    restart: always
#    build: ./nginx/
#    volumes:
#       - ./mysite/myapp/static:/static/
#    depends_on: 
#       - web
#    ports:
#       - 80:80
#       - 443:443
#    links:
#       - web:web

  redis:
   image: redis:latest
   expose:
      - 6379

  caddy:
   image: caddy:latest
   restart: unless-stopped
   depends_on: 
     - web
   links:
     - web:web
   ports:
     - "80:80"
     - "443:443"
   volumes:
     - $PWD/Caddyfile:/etc/caddy/Caddyfile
     - $PWD/mysite/myapp/static:/srv/wasm/
     - caddy_data:/data
     - caddy_config:/config

volumes:
 caddy_data:
 caddy_config:




