# Generated by Django 3.2.4 on 2021-06-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionmodel',
            name='suggestion2',
            field=models.CharField(default='bob', max_length=240),
        ),
    ]
