# Generated by Django 3.2.4 on 2021-06-07 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_remove_suggestionmodel_suggestion2'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionmodel',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
