# Generated by Django 3.2.4 on 2021-06-07 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_commentmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='suggestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.suggestionmodel'),
            preserve_default=False,
        ),
    ]
